services:
  - type: web
    name: rh-control
    runtime: python
    rootDir: application-rh
    plan: free
    buildCommand: python -m pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: RH_DATABASE_PATH
        value: /tmp/rh_control.sqlite
